---
title: "progress-report"
author: "Prudvik seemakurthi"
output: html_document
date: "2025-11-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)
tables
```

```{r}
head(tables[[1]], 3)
```

look at the people data set from lahmna

```{r}
library(Lahman)
library(tidyverse)

head(HallOfFame)
view(HallOfFame)

view(People)
```

extracting column names
```{r}
tables <- tables[[1]]

colnames(tables) <- tables[1, ] |> unlist() |> as.character()
raw_table <- tables[-1, ]
```

preparing Hall of Fame voting table 

```{r}
hof_raw <- raw_table %>%
  select(Rk, Name, YoB, Votes, `%vote`, HOFm, HOFs, Yrs, WAR, WAR7, JAWS) %>%
  mutate(
    `%vote` = parse_number(`%vote`),
    across(
      .cols = c(Rk, YoB, Votes, HOFm, HOFs, Yrs, WAR, WAR7, JAWS),
      .fns  = ~ suppressWarnings(parse_number(.x))
    ),
    Name = str_trim(Name)
  )
```

preparing Lahman People table for joining 

```{r}
people_tbl <- Lahman::People %>%
  mutate(fullName = paste(nameFirst, nameLast))
```

Merging Hall of Fame data with player IDs
```{r}
hof_joined <- hof_raw %>%
  left_join(
    people_tbl %>% select(playerID, fullName),
    by = c("Name" = "fullName")
  )
```

Final cleaned dataset for export
```{r}

ballot_max <- max(hof_joined$Votes, na.rm = TRUE)

hof_cleaned <- hof_joined %>%
  mutate(
    ballots  = ballot_max,
    needed   = round(ballots * 0.75, 2),
    votes    = Votes,
    inducted = if_else(`%vote` >= 75, "Y", "N")
  ) %>%
  mutate(
    yearID      = 2025,
    votedBy     = "BBWAA",
    category    = "Player",
    needed_note = NA
  ) %>%
  select(
    playerID, yearID, votedBy, ballots,
    needed, votes, inducted, category, needed_note
  )


```

```{r}
head(hof_cleaned, 10)
```

