---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(Lahman)
```

# Lab report #4

```{r}
#Gather the HTML of the data being scrapped

url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
html
```


```{r}
#Gather all the tables from the HTML dataset

tables <- html %>% html_table(fill=TRUE)
tables
```

```{r}
# Filter for only the voting table
votes <- tables[[1]]
head(votes)
```

```{r}
# Build the data frame]
actual_col_names <- votes[1, ]
colnames(votes) <- actual_col_names
votes <- votes[-1, ]
```


```{r}
#Save the data frame (the intial Data)
write.csv(votes, "C:\\Users\\nvnpr\\Downloads\\voting.csv")
```

```{r}
#Preview of the saved Data from the scrapped data
head(votes)

```

```{r}
# Preview of the Lahman Data
head(HallOfFame)
```


```{r}

#Clean the data

votes <- votes |> select(Rk, Name, YoB, Votes, `%vote`, HOFm, HOFs, Yrs, WAR, WAR7, JAWS)

votes <- votes |> mutate(`%vote` = parse_number(`%vote`),across(c(Rk, YoB, Votes, HOFm, HOFs, Yrs, WAR, WAR7, JAWS), as.numeric),Name = str_trim(Name))

```

```{r}
# Join the dataset to get player ID:

votes <- votes |>left_join(Lahman::People |>  mutate(fullName = paste(nameFirst, nameLast)) |> select(playerID, fullName),by = c("Name" = "fullName"))

```

```{r}

#  Add yearID
votes <- votes |> mutate(yearID = 2025)

# Add votedBy
votes <- votes |> mutate(votedBy = "BBWAA")

#  Calculate total ballots
votes <- votes |> mutate(Votes = as.numeric(Votes))  
votes <- votes |> mutate(votes = Votes)               
votes <- votes |> mutate(ballots = max(votes, na.rm = TRUE))

#  Calculate needed votes (75% of ballots)
votes <- votes |> mutate(needed = round(0.75 * ballots))

#  Determine inducted status
votes <- votes |> mutate(inducted = if_else(`%vote` >= 75, "Y", "N"))

#  Add category column
votes <- votes |> mutate(category = "Player")


#  Select only the final columns
votes <- votes |>
  select(playerID, yearID, votedBy, ballots, needed,
         votes, inducted, category)


votes

```


