---
title: "progress-report-jyotikasharma12"
author: "Jyotika Sharma"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(Lahman)
library(dplyr)
library(readr)
library(stringr)
library(tidyverse)

url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html, fill = TRUE)

raw <- tables[[1]]

col_names <- raw[1, ] |> unlist() |> as.character()
colnames(raw) <- col_names
raw <- raw[-1, ]

data <- raw |> 
  select(
    Rk, Name, YoB, Votes, `%vote`, HOFm, HOFs, Yrs, WAR, WAR7, JAWS
  ) |>
  mutate(
    `%vote` = parse_number(`%vote`),
    across(c(Rk, YoB, Votes, HOFm, HOFs, Yrs, WAR, WAR7, JAWS),
           ~ suppressWarnings(parse_number(.x))),
    Name = str_trim(Name)
  )

People <- Lahman::People |> 
  mutate(fullName = paste(nameFirst, nameLast))

data <- data |> 
  left_join(People |> select(playerID, fullName),
            by = c("Name" = "fullName"))

cleaned <- data |> 
  mutate(
    yearID = 2025,
    votedBy = "BBWAA",
    ballots = max(Votes, na.rm = TRUE),
    needed = round(0.75 * ballots),
    votes = Votes,
    inducted = ifelse(`%vote` >= 75, "Y", "N"),
    category = "Player",
    needed_note = NA
  ) |> 
  select(playerID, yearID, votedBy, ballots, needed, votes, inducted, category, needed_note)

head(cleaned, 10)

readr::write_csv(cleaned, file = "HallOfFame_2025_cleaned.csv")

```

